Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    #UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.tableName}
      #PointInTimeRecoverySpecification:
      #PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
